### ISSUE TITLE
Uso degli esercizi

### ISSUE THREAD

**Issue by Daniele-Tentoni** [antony945/InformaticaRipetizioni#1]
Ciao @antony945 ,
non sapendo come altro contattarti, dato che ti ho trovato qui su GitHub, ti scrivo questa issue.

Posso prendere i tuoi esercizi che hai pubblicato su questo repo per fare delle ripetizioni a mia volta ad un ragazzo che ha bisogno di Informatica per una quarta liceo scientifico?

Inoltre, nel caso tu avessi altri esercizi da sottoporre, li potresti ricaricare in questo repo? Ti lascio in allegato il mio repo che uso io: [Esercizi Ripetizioni](https://github.com/Daniele-Tentoni/esercizi_ripetizioni)

Daniele Tentoni

**Comment by antony945** [comment]
Ciao, puoi prendere tutto quello che ti serve, figurati! Considera che in realtà sono un semplice studente di Ingegneria e ho dato ripetizioni solo per qualche mese, quindi i file non sono curatissimi e magari hanno qualche errore, ma se ti servono usali pure.

Antonio Franzoso

**Comment by Daniele-Tentoni** [comment]
Quindi proprio nella mia stessa situazione! Dal fatto che avevi vari repository del genere credevo che fossi un professore, grazie mille.
